# Generated by Django 4.1.3 on 2023-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='停车位号')),
                ('level', models.CharField(default='', max_length=255, verbose_name='停车层')),
                ('plate', models.CharField(blank=True, default='', max_length=255, verbose_name='车牌号')),
                ('car_type', models.IntegerField(blank=True, default=1, verbose_name='车俩类型')),
                ('long_lease_user', models.CharField(blank=True, default='', max_length=255, verbose_name='长租用户')),
                ('pic', models.ImageField(blank=True, default='', upload_to='parking_space_number/', verbose_name='车牌图片路径')),
                ('flag', models.IntegerField(default=0, verbose_name='是否可用')),
            ],
            options={
                'db_table': 'app_Parking',
                'unique_together': {('number', 'level')},
            },
        ),
    ]
