# Generated by Django 4.1.3 on 2023-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='car_type',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='车俩类型'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='long_lease_user',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='长租用户'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='parking_space_number/', verbose_name='车牌图片路径'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='车牌号'),
        ),
    ]
