# Generated by Django 4.1.3 on 2023-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_parking_car_type_alter_parking_long_lease_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='', max_length=255, verbose_name='车牌')),
                ('number', models.IntegerField(default=1, verbose_name='停车位号')),
                ('level', models.CharField(default='', max_length=255, verbose_name='停车层')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('charging_fee', models.IntegerField(default='', verbose_name='充电费用')),
                ('parking_fee', models.IntegerField(default='', verbose_name='停车费用')),
                ('total_fee', models.IntegerField(default='', verbose_name='总共的费用')),
                ('user_phone', models.CharField(default='', max_length=255, verbose_name='用户手机号')),
                ('flag', models.IntegerField(default='1', verbose_name='是否已经停车')),
                ('paid', models.IntegerField(default='1', verbose_name='是否已经支付')),
                ('address', models.CharField(default='', max_length=255, verbose_name='停车场位置')),
            ],
        ),
    ]
