# Generated by Django 4.1.3 on 2023-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='停车场位置'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charging_fee',
            field=models.IntegerField(default='', null=True, verbose_name='充电费用'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flag',
            field=models.IntegerField(choices=[(1, '待停放'), (0, '已停放')], default='1', verbose_name='是否已经停车'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.IntegerField(choices=[(1, '未支付'), (0, '已支付')], default='1', verbose_name='是否已经支付'),
        ),
        migrations.AlterField(
            model_name='order',
            name='parking_fee',
            field=models.IntegerField(default='', null=True, verbose_name='停车费用'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_fee',
            field=models.IntegerField(default='', null=True, verbose_name='总共的费用'),
        ),
    ]
