# Generated by Django 4.1.3 on 2023-03-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_address_alter_order_charging_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='charging_fee',
        ),
    ]
