# Generated by Django 4.1.3 on 2023-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_charging_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('add_logentry', '日志增加'), ('change_logentry', '日志修改'), ('delete_logentry', '删除日志')),
            },
        ),
    ]
