# Generated by Django 4.1.3 on 2023-04-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
