# Generated by Django 4.1.3 on 2023-04-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_permission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parking',
            table='停车场',
        ),
    ]
