# Generated by Django 4.1.3 on 2023-04-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_parking_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parking',
            table='app_Parking',
        ),
    ]
