# Generated by Django 4.1.3 on 2023-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_parking_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name': '停车场管理'},
        ),
        migrations.AlterField(
            model_name='order',
            name='flag',
            field=models.IntegerField(choices=[(2, '进行中'), (1, '待停放'), (0, '已停放')], default='1', verbose_name='是否已经停车'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.IntegerField(choices=[(2, '订单进行中'), (1, '未支付'), (0, '已支付')], default='1', verbose_name='是否已经支付'),
        ),
    ]
