# Generated by Django 4.1.3 on 2023-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_options_alter_parking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.IntegerField(choices=[(2, '进行中'), (1, '未支付'), (0, '已支付')], default='1', verbose_name='是否已经支付'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='car_type',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='车辆类型'),
        ),
    ]
