# Generated by Django 4.1.3 on 2023-05-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_paid_alter_parking_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='car_type',
            field=models.IntegerField(blank=True, choices=[(1, '普通汽车'), (0, '新能源汽车')], default=1, null=True, verbose_name='车辆类型'),
        ),
    ]
